Dedupe impressions into development
splitio/.net-core-client pull request #170
Opened 2020-10-05 17:55 UTC by sanzmauro

# .NET SDK

## What did you accomplish?

## How do we test the changes introduced in this PR?

## Extra Notes

2020-10-05 18:14 UTC, NicoZelaya approved these changes

2020-10-05 21:22 UTC, mmelograno requested changes

2020-10-05 21:22 UTC, mmelograno commented on src/Splitio-net-core/Domain/ConfigurationOptions.cs
> +        public ImpressionMode? ImpressionMode { get; set; }
according to the spec it is `ImpressionsMode`

2020-10-05 21:22 UTC, mmelograno commented on src/Splitio-net-core/Services/Cache/Lru/CacheEnumerator.cs
> +﻿// Copyright (c) Mark Davis. All rights reserved.
I think that you are missing here: license and repo url

2020-10-05 21:22 UTC, mmelograno commented on src/Splitio-net-core/Services/Cache/Lru/CacheEnumerator.cs
> +﻿// Copyright (c) Mark Davis. All rights reserved.
You can follow this as an example https://github.com/splitio/javascript-client/blob/development/src/utils/lrucache/linkedlist.js#L2

2020-10-05 21:22 UTC, mmelograno commented on src/Splitio-net-core/Services/Cache/Lru/Node.cs
> +﻿// Copyright (c) Mark Davis. All rights reserved.
same here

2020-10-05 21:22 UTC, mmelograno commented on src/Splitio-net-core/Services/Impressions/Classes/ImpressionsManager.cs
> +            if (_addPreviousTime && _impressionsObserver != null)
you could add this validation in the constructor and only evaluate one of this here (false or true)

2020-10-05 21:22 UTC, mmelograno commented on src/Splitio-net-core/Services/Shared/Classes/ConfigService.cs
> +                _log.Warn($"{configName} minumum allowed value: {minAllowed}");
wording: minimum

2020-10-06 19:26 UTC, sanzmauro commented
@mmelograno changes applied!

2020-10-06 19:29 UTC, mmelograno approved these changes
LGTM!

2020-10-06 19:30 UTC, merged